steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/curl-chemist:$COMMIT_SHA', '.']

  # Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/curl-chemist:$COMMIT_SHA']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'curl-chemist'
      - '--image'
      - 'gcr.io/$PROJECT_ID/curl-chemist:$COMMIT_SHA'
      - '--port'
      - '8000'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--no-cpu-throttling'
      # Pull secrets from Google Secret Manager
      - '--set-secrets=GOOGLE_OAUTH_CREDENTIALS=gmail-oauth-credentials:latest,GOOGLE_OAUTH_TOKEN=gmail-oauth-token:latest'

  # Step 4: Deploy Firestore Indexes
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -f firestore.indexes.json ]; then
          gcloud firestore indexes composite create --file=firestore.indexes.json --project=$PROJECT_ID || echo "Indexes already exist or error occurred"
        fi

images:
  - 'gcr.io/$PROJECT_ID/curl-chemist:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
